spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update